---
title: "Data Processing"
output: html_document
editor_options: 
  chunk_output_type: console
---
#Load Packages
```{r}
library(Seurat)
library(harmony)
library(Nebulosa)
library(biomaRt)
library(dplyr)
gene_lists <- readRDS("/premiumDisk/khoh/Github/scTME/data/gene_lists.rds")
source('/premiumDisk/khoh/Github/scTME/R/score_sig.R', echo=TRUE)
```


#@ Myeloid
```{r}
#PDACTraining <- readRDS("~/premDisk/khoh/PDACTrainingSet2021v3.rds")
Myeloid<-subset(PDACTraining,CellType1%in%c("Myeloid"))
DefaultAssay(Myeloid)<-"SCT"
list_full<-SplitObject(Myeloid,split.by = "Dataset")
rm(full)
high <- WhichCells(pancreas_merged, idents = c("Myeloid"))
DimPlot(pancreas_merged,cells.highlight = high,reduction = "tsne") +NoLegend()                        
int.features <- SelectIntegrationFeatures(object.list = list_full, nfeatures = 4000)
Powers <- list_full$Powers
list_full$Powers <- NULL
Myeloid <- merge(Powers, y = c(list_full),  project = "Myeloid", merge.data = TRUE)
VariableFeatures(Myeloid) <- int.features
Myeloid <- RunPCA(object = Myeloid, assay = "SCT", npcs = 50)
Myeloid <- RunHarmony(object = Myeloid,
                                    assay.use = "SCT",
                                    reduction = "pca",
                                    dims.use = 1:50,
                                    group.by.vars = c("Patient"),
                                    plot_convergence = TRUE)
Myeloid <- RunUMAP(object = Myeloid, assay = "SCT", 
                   reduction = "harmony", 
                   min.dist = 0.4,
                   local.connectivity = 5L,
                   negative.sample.rate = 20,
                   n.neighbors = 300,
                   dims = 1:10)
Myeloid <- FindNeighbors(object = Myeloid, assay = "SCT", reduction = "harmony", dims = 1:10)
Myeloid <- FindClusters(object = Myeloid, resolution = 0.4) #old
DimPlot(Myeloid,label=T,reduction = "umap")
Myeloid<-Seurat::FindSubCluster(Myeloid,cluster=1,graph.name ="SCT_snn",resolution = 0.2)
table(Myeloid$sub.cluster)
DimPlot(Myeloid,label=T,reduction = "umap",group.by = "sub.cluster")
Myeloid<-RunTSNE(Myeloid,reduction = "harmony",dims = 1:10)
DimPlot(Myeloid,reduction = "tsne",label=T)
Myeloid<-score_sig(Myeloid)
plot_density(Myeloid,features =c( "Bernard_Lymphocyte","CIBERSORT.Macrophages.M1","Tuveson_AlternativeMac","Tuveson_ConventionalDC","Tuveson_ResidentMac","Tuveson_LangerhansDC_A","Tuveson_LangerhansDC_B","Tuveson_ClassicalMonocyte","Villani_CD1C.DC","Bernard_Dendritic","CIBERSORT.Macrophages.M2","Villani_pan.mono"),size = 0.1,method = "wkde",reduction = "umap")
```

#>>   FindMarkers - Heatmap
```{r}
Myeloid<-BuildClusterTree(Myeloid,dims = 1:10,reorder = T)
PlotClusterTree(Myeloid)
table(Myeloid$seurat_clusters)
Idents(Myeloid)<-"sub.cluster"
small <- subset(Myeloid, downsample = 600)
DefaultAssay(small)<-"RNA"
small<-NormalizeData(small)
small<-ScaleData(small,rownames(small))
fullmarkers <- FindAllMarkers(Myeloid,min.pct = 0.1,min.diff.pct = 0.1,test.use = "MAST",only.pos = F)
top10 <- fullmarkers %>% group_by(cluster) %>% top_n(n = 20, wt = avg_log2FC)
toppval <- fullmarkers %>% group_by(cluster) %>% top_n(n = -20, wt = p_val_adj)
DoHeatmap(small, features = top10$gene,label=T) + NoLegend()
DoHeatmap(small, features = toppval$gene,label=T) + NoLegend()
DimPlot(pancreas_merged,group.by = c("Dataset","Condition","CellType1"))
plot_density(Myeloid, c("MS4A4A","CD14","MAFB","ITGAE","CSTB","FCER1A","CD1C","S100A8","PLD3","CCL7","CCL19","SPP1","CD1C","FCGR3A","CD163","IL17RA","IRF8","BATF3","NOTCH2","KLF4","RUNX1","CLEC9A","EPCAM","MMP9","SPI1","CBFB","GPR34","HSPA6","ITGAX"),size = 0.1,reduction = "umap")
plot_density(Myeloid, c("MMP14","FCGR3A","GPR34","CX3CR1","MS4A4A","HSP1A1"),size = 0.1,reduction = "umap",method = "wkde")
#+=====================
top10 <- fullmarkers %>% group_by(cluster) %>% top_n(n = 5, wt = avg_log2FC)
VlnPlot(Myeloid,features=unique(top10$gene))
DimPlot(Myeloid,label = T)

new.cluster.ids <-  #new 2022
 c(  "LAMP3.DC", #5  --
    "Resident.Mac", #1_0 --
     "mDC",#1_1 --
"Classical.Mono",#2 --
     "FSIP2.TAM",#0
"SPP1.TAM",#3 infg
"GRN.TAM")#4===

names(new.cluster.ids) <- levels(Myeloid)
Myeloid <- RenameIdents(Myeloid, new.cluster.ids)
Myeloid$CellType2<-Idents(Myeloid)
#saveRDS(Myeloid,"Myeloid_Subset202.rds")

DotPlot(Myeloid,features=c("S100A12","CD14","FCGR3A","CD163","APOC1","CCL2","CCL18","MMP9","CX3CR1","SELENOP","CSF1R","FCGR3B","C1QA","CLEC10A","IL1B","LAMP3"),group.by = "CellType2")+RotatedAxis()
```
