---
title: "Data Processing"
output: html_document
editor_options: 
  chunk_output_type: console
---
#Load Packages
```{r}
library(Seurat)
library(harmony)
library(Nebulosa)
library(biomaRt)
library(dplyr)
gene_lists <- readRDS("/premiumDisk/khoh/Github/scTME/data/gene_lists.rds")
source('/premiumDisk/khoh/Github/scTME/R/score_sig.R', echo=TRUE)
source('/premDisk/khoh/Github/scTME/R/pseudobulk_score.R', echo=TRUE)
source('/premDisk/khoh/Github/scTME/R/pseudobulk.R', echo=TRUE)
```

#@ Epithelium 
```{r}
Epi<-subset(PDACTraining,CellType1%in%c("Epithelium"))
list_full<-SplitObject(Epi,split.by = "Dataset")

int.features <- SelectIntegrationFeatures(object.list = list_full, nfeatures = 3000)
Powers <- list_full$Powers
list_full$Powers <- NULL
Epi <- merge(Powers, y = c(list_full),  project = "Epithelium", merge.data = TRUE)
rm(list_full)
VariableFeatures(Epi) <- int.features
Epi <- RunPCA(object = Epi, assay = "SCT", npcs = 30)
Epi <- RunHarmony(object = Epi,
                                    assay.use = "SCT",
                                    reduction = "pca",
                                    dims.use = 1:20,
                                    group.by.vars = c("Dataset"),
                                    plot_convergence = TRUE)
ElbowPlot(Epi,ndims=30,reduction="harmony")
Epi <- RunUMAP(object = Epi, assay = "SCT", 
                   reduction = "harmony", 
                   min.dist = 0.1,
               negative.sample.rate = 10,
                local.connectivity = 100,
                   n.neighbors = 1000,
                   dims = 1:8)
Epi <- FindNeighbors(object = Epi, assay = "SCT", reduction = "harmony", dims = 1:8)
Epi <- FindClusters(object = Epi, resolution = 0.6)#0.15 - latest
DimPlot(Epi,label=T)
Epi<-RunTSNE(Epi,reduction = "harmony",dims = 1:14)
DimPlot(Epi,label=T,reduction = "tsne")
```

#>> Epi Heatmap
```{r}
Epi<-BuildClusterTree(Epi,dims = 1:14,reorder = T)
PlotClusterTree(Epi)
table(Epi$CellType2)
x<-which(Epi$CellType2%in%"EMT.Duct")
Epi$CellType2[x]<-"Neoplastic"
x<-which(Epi$CellType2%in%"HSP.Duct")
Epi$CellType2[x]<-"Normal.Duct"
Idents(Epi)<-"CellType2"
small <- subset(Epi, downsample = 3000)
DefaultAssay(small)<-"RNA"
small<-NormalizeData(small)
small<-ScaleData(small,vars.to.regress = "Dataset")
fullmarkers <- FindAllMarkers(small,min.pct = 0.2,min.diff.pct = 0.1,test.use = "MAST",only.pos = F)
write.csv(fullmarkers,"EpiCellType2Markers.csv")
top10 <- fullmarkers %>% group_by(cluster) %>% top_n(n = 30, wt = avg_log2FC)
toppval <- fullmarkers %>% group_by(cluster) %>% top_n(n = -10, wt = p_val_adj)

#Idents(small)<-"seurat_clusters"
DoHeatmap(small, features = top10$gene,label=T) + NoLegend()
DoHeatmap(small, features = toppval$gene,label=T) + NoLegend()
a<-FindMarkers(small,ident.1 = 5)
a%>%top_n(n=10,wt=avg_log2FC)
a%>%top_n(n=-10,wt=p_val_adj)
Idents(Epi)<-"seurat_clusters"
new.cluster.ids <- 
 c( "Normal.Duct",#0
    "Neoplastic",#1
    "Metaplastic",#2
    "Acinar",#3======
    "HSP.Duct",#4
    "EMT.Duct"#5
)
names(new.cluster.ids) <- levels(Epi)
Epi <- RenameIdents(Epi, new.cluster.ids)
Epi$CellType2<-Idents(Epi)
VlnPlot(Epi,features=c("CDH11","FN1","PRSS1","AMBP","KRT17","TFF3","SOX9","PDX1","AKAP12","mesenchymal","epithelial","ZEB1"),pt.size = 0)
FeaturePlot(Epi,features=c("CDH11","FN1","KRT17","TFF3","OLFM4"),order=T)
DimPlot(Epi,label=T)
saveRDS(Epi,"Epi_Subset2021.rds")
```

# >>Epi Scores
```{r}
#====================================
Epi<-score_sig(Epi)
epi.meta<-Epi@meta.data
saveRDS(epi.meta,"Epi.Meta.rds")
plot_density(Epi,features =c( "Moffitt.Basal.25","Moffitt.Classical.25","Qadir_Centroacinar","Qadir_AcinarTrans1","Qadir_AcinarTrans2","Qadir_MigrateProgen","Qadir_StressProgen","Qadir_SmallDucts","ADM","AMBP","MUC1","TFF3","KRT17","CEACAM6","PRSS1","EPCAM","Montada.tDuct","Montada.Centroacinar","Montada.Hypoxic","acinar","ductal","Notta.BasalA","Notta.BasalB","Notta.ClassicalA","Notta.ClassicalB","Califano_Lineage","Califano_Morpho","RaghavanBasal"),size=0.1,reduction = "umap",method = "wkde")

```

#>> Epithelium Tumor - Only
```{r}
DefaultAssay(Epi)<-"SCT"
Tumor<-subset(Epi,Condition %in%"Tumor")
Tumor<-subset(Tumor,CellType2 %in%c("Neoplastic","Metaplastic","Normal.Duct","Acinar"))
table(Tumor$CellType2) #originally 40,369 cells
#Tumor<-subset(Tumor, nFeature_SCT>1000) #12,871 cells
Tumor$MT<-"Classical"
x<-Tumor$Patient%in%c("peng_T12","peng_T11","peng_T16","peng_T19","PDAC1","peng_T21","peng_T23","peng_T8","peng_T9","peng_T7")
Tumor$MT[x]<-"Basal"
x<-Tumor$Patient%in%c("peng_T5","PDAC2","peng_T13","peng_T22","peng_T15")
Tumor$MT[x]<-"Mixed"
table(Tumor$MT)
#===========================
x<-Tumor$CellType2%in%c("EMT.Duct")
Tumor$CellType2[x]<-"Neoplastic"
x<-Tumor$CellType2%in%c("HSP.Duct")
Tumor$CellType2[x]<-"Normal.Duct"
table(Tumor$CellType2)
Tumor$CellType2<-droplevels(Tumor$CellType2)

list_full<-SplitObject(Tumor,split.by = "Dataset")
int.features <- SelectIntegrationFeatures(object.list = list_full, nfeatures = 600)
Powers <- list_full$Powers
list_full$Powers <- NULL
Tumor <- merge(Powers, y = c(list_full),  project = "Epithelium", merge.data = TRUE)
rm(Powers)
rm(list_full)
VariableFeatures(Tumor)<- int.features
Tumor <- RunPCA(object = Tumor, assay = "SCT", npcs = 20)
Tumor <- RunHarmony(object = Tumor,
                                    assay.use = "SCT",
                                    reduction = "pca",
                                    dims.use = 1:20,
                                    group.by.vars = c("Dataset"),
                                    plot_convergence = TRUE)

Tumor <- RunUMAP(object = Tumor, assay = "SCT", 
                   reduction = "pca", 
                  
                local.connectivity =30,
                   n.neighbors = 300,
                negative.sample.rate = 30,
                n.components = 3,
                   dims = 1:10)
Tumor<-RunUMAP(object = Tumor,assay="SCT",dims = 1:5,  negative.sample.rate = 10,reduction = "pca",  n.components = 3, local.connectivity =30, n.neighbors = 300,min.dist = 0.2)
DimPlot(Tumor,label=T)
Tumor <- FindNeighbors(object = Tumor, assay = "SCT", reduction = "pca", dims = 1:5)
Tumor <- FindClusters(object = Tumor, resolution = 0.2)
DimPlot(Tumor,label=T)
DimHeatmap(Tumor,dims = 1:5,reduction = "harmony")

Tumor<-score_sig(Tumor)
Tumor<-RunTSNE(Tumor,reduction = "harmony",dims = 1:4)

#saveRDS(Tumor,"TumorSubset2021.rds")
```

#@ Neoplasm Subset
```{r}
neo<-subset(Tumor,seurat_clusters%in%c(1))
DimPlot(neo)
neo<-FindVariableFeatures(neo,nfeatures = 300)
neo <- RunPCA(object = neo, assay = "SCT", npcs = 20)

ElbowPlot(neo,ndims=20,reduction="pca")
neo <- RunUMAP(object = neo, assay = "SCT", 
                   reduction = "pca", 
                   min.dist = 0.1,
                local.connectivity =10,
                   n.neighbors = 30,
                negative.sample.rate = 5,
                n.components = 2,
                   dims = 1:5)
neo<-RunUMAP(neo,dims=1:5)

neo<-FindNeighbors(neo,reduction = "pca",dims=1:5)
neo<-FindClusters(neo,resolution = 0.1)
DimPlot(neo)
DimPlot(neo,group.by="MT")
FeaturePlot(neo,features=c("Moffitt.Basal.25"),order=T)
VlnPlot(neo,features=c("Moffitt.Classical.25","Moffitt.Basal.25","RaghavanIntermediate"),group.by="MT") #Figure 4
```

# Subtype ScatterPlots
```{r}
subset<-c("peng_T17","peng_T6","peng_T4","peng_T3","peng_T24","peng_T20","peng_T2","peng_T18","peng_T14","peng_T1","peng_T10","peng_T15","peng_T22","peng_T13","PDAC2","peng_T5","peng_T7","peng_T9","peng_T8","peng_T23","peng_T21","PDAC1","peng_T19","peng_T16","peng_T11")
neo<-subset(neo,Patient%in%subset)
FeatureScatter(neo,feature1 = "Moffitt.Basal.25",feature2="Moffitt.Classical.25",group.by = "MT") 
p1<-FeatureScatter(subset(neo,MT%in%"Basal"),feature1 = "Moffitt.Basal.25",feature2="Moffitt.Classical.25",group.by = "MT",pt.size = 0.5) 
p2<-FeatureScatter(subset(neo,MT%in%"Classical"),feature1 = "Moffitt.Basal.25",feature2="Moffitt.Classical.25",group.by = "MT",pt.size = 0.5) 
p3<-FeatureScatter(subset(neo,MT%in%"Mixed"),feature1 = "Moffitt.Basal.25",feature2="Moffitt.Classical.25",group.by = "MT",pt.size = 0.5) 
cowplot::plot_grid(p1,p2,p3)
source('/premDisk/khoh/Github/scTME/R/pseudobulk_score.R', echo=TRUE)
source('/premDisk/khoh/Github/scTME/R/pseudobulk.R', echo=TRUE)
newdf<-pseudobulk(neo)
output<-pseudobulk_score(newdf)
samples<-output[[1]]
genes<-output[[2]]
expression<-output[[3]]
samplesToPlot <- which((!samples$note %in% "OK"))
```

# Pseudobulk Sample ScatterPlot
```{r}
samples$MT<-"Classical"
x<-samples$Patient%in%c("peng_T12","peng_T11","peng_T16","peng_T19","PDAC1","peng_T21","peng_T23","peng_T8","peng_T9","peng_T7")
samples$MT[x]<-"Basal"
x<-samples$Patient%in%c("peng_T5","PDAC2","peng_T13","peng_T22","peng_T15")
samples$MT[x]<-"Mixed"

#======================================== 
p<-ggplot(samples, aes(Moffitt.F6_BasalLike.top25, Moffitt.F8_Classical.top25,label=Patient)) +geom_text_repel()+
  geom_point(aes(color = MT), size = 3,alpha=0.5)+RotatedAxis()+NoLegend()
print(p)
```


## 3D UMAP
```{r}
library(plotly)
#DefaultAssay(df2)<-"SCT"
# Prepare a dataframe for cell plotting
plot.data <- FetchData(object = Tumor, vars = c("UMAP_1", "UMAP_2", "UMAP_3","Phase", "seurat_clusters","orig.ident","CellType2","Condition"))

# Make a column of row name identities (these will be your cell/barcode names)
plot.data$label <- paste(rownames(plot.data))
plot.data$label <- paste(plot.data$seurat_clusters)
# Plot your data, in this example my Seurat object had 21 clusters (0-20)
plot_ly(data = plot.data, 
        x = ~UMAP_1, y = ~UMAP_2, z = ~UMAP_3, 
        #  color = ~`pathologic diagnoses`, 
        color = ~seurat_clusters, 
        colors = c("darkturquoise",
                   "red",
                  
                     "hotpink",
                   "dodgerblue"),
        type = "scatter3d", 
        mode = "markers", 
        size=2,
        opacity=0.25,
       # add_markers(size = 8) ,
        #  symbol = ~SCT_snn_res0.002, symbols = c('circle','x','o'),
        marker = list(size = 1, width=1), # controls size of points
        text=~label, #This is that extra column we made earlier for which we will use
        hoverinfo="text")

```

## 3D UMAP
```{r}
library(plotly)
#DefaultAssay(df2)<-"SCT"
# Prepare a dataframe for cell plotting
plot.data <- FetchData(object = Tumor, vars = c("UMAP_1", "UMAP_2", "UMAP_3","Phase", "seurat_clusters","orig.ident","CellType2","Condition","KRT17","TFF3","OLFM4","HOXB2","AMBP","MUC1","VCAM1","MMP7","CXCL14","TIMP3","COL18A1","LAMC1","SEMA3B","Pei_ADM","Moffitt.Basal.25","Moffitt.Classical.25","RaghavanIntermediate","SPP1","PTCH1","Puram_epi.diff","MMP7","OLFM4","SMO","EMT","peripheral.panc","central.panc","CLDN10","SH3YL1","MUC6","PRSS1","PDX1","YAP1","SOX9","SOX3","SOX6"))

# Make a column of row name identities (these will be your cell/barcode names)
plot.data$label <- paste(rownames(plot.data))
plot.data$label <- paste(plot.data$CellType2)
# Plot your data, in this example my Seurat object had 21 clusters (0-20)
plot_ly(data = plot.data, 
        x = ~UMAP_1, y = ~UMAP_2, z = ~UMAP_3, 
        #  color = ~`pathologic diagnoses`, 
        color = ~PRSS1, 
        colors = c("grey",
                   "red"),
        type = "scatter3d", 
        mode = "markers", 
        size=0.05,
        opacity=0.5,
        #  symbol = ~SCT_snn_res0.002, symbols = c('circle','x','o'),
        marker = list(size = 1, width=1), # controls size of points
        text=~label, #This is that extra column we made earlier for which we will use
        hoverinfo="text")
plot_ly(data = plot.data, 
        x = ~UMAP_1, y = ~UMAP_2, z = ~UMAP_3, 
        color = ~Moffitt.Classical.25, 
        colors = c("grey",
                   "darkblue"),
        type = "scatter3d", 
        mode = "markers", 
        size=0.05,
        opacity=0.5,
        marker = list(size = 1, width=1), # controls size of points
        text=~label, #This is that extra column we made earlier for which we will use
        hoverinfo="text")

plot_ly(data = plot.data, 
        x = ~UMAP_1, y = ~UMAP_2, z = ~UMAP_3, 
        color = ~Moffitt.Basal.25, 
        colors = c("grey",
                   "orange"),
        type = "scatter3d", 
        mode = "markers", 
        strokes = "red",
        size=0.1,
        opacity=0.5,
        #  symbol = ~SCT_snn_res0.002, symbols = c('circle','x','o'),
        marker = list(size = 1, width=1), # controls size of points
        text=~label, #This is that extra column we made earlier for which we will use
        hoverinfo="text")
plot_ly(data = plot.data, 
        x = ~UMAP_1, y = ~UMAP_2, z = ~UMAP_3, 
        color = ~MUC6, 
        colors = c("grey",
                   "darkred"),
        type = "scatter3d", 
        mode = "markers", 
        size=0.05,
        opacity=0.8,
        #  symbol = ~SCT_snn_res0.002, symbols = c('circle','x','o'),
        marker = list(size = 1, width=1), # controls size of points
        text=~label, #This is that extra column we made earlier for which we will use
        hoverinfo="text")
```



