---
title: "GlobalExpression"
output: html_document
---
```{r}
library(Seurat)
library(tidyverse)  
library(biomaRt)
library(dplyr)
```

# Global CellType2 Secretome/Contact/ECM/TF DotPlots
```{r}
PDACTraining <- readRDS("/premDisk/khoh/Github/scTME/PDACTrainingSet2021v3.rds")
PDACTraining$CellType2<-as.character(PDACTraining$CellType1)
PDACTraining$CellType2[colnames(Myeloid)]<-(as.character(Myeloid$CellType2))
PDACTraining$CellType2[colnames(Stroma)]<-(as.character(Stroma$CellType2))
PDACTraining$CellType2[colnames(Endo)]<-(as.character(Endo$CellType2))
PDACTraining$CellType2[colnames(Lymphocytes)]<-(as.character(Lymphocytes$CellType2))
PDACTraining$CellType2[colnames(Epi)]<-(as.character(Epi$CellType2))
table(PDACTraining$CellType2)
#========================================================== # Correct Epithelium nomenclature
x<-which(PDACTraining$CellType2%in%"EMT.Duct")
PDACTraining$CellType2[x]<-"Neoplastic"
x<-which(PDACTraining$CellType2%in%"HSP.Duct")
PDACTraining$CellType2[x]<-"Normal.Duct"
x<-which(PDACTraining$CellType2%in%"LEFTY.Duct")
PDACTraining$CellType2[x]<-"Metaplastic"
#========================================================== # create vector of cell type 2 labels
PDACTrainingCellType2<-PDACTraining$CellType2
#saveRDS(PDACTrainingCellType2,"PDACTrainingCellType2Label.rds")
PDACTrainingCellType2 <- readRDS("/premDisk/khoh/PDACTrainingCellType2Label.rds")
PDACTraining$CellType2<-PDACTrainingCellType2
#======================================================================== # remove unwanted gropus for analysis
x<-which(PDACTraining$CellType2%in%c("IL11.CAF","Myocyte","Fibroblast","Endocrine","Prolif.Lymph","Progenitor.Lymph"))
PDACSubset1<-PDACTraining[,-x]
table(PDACTraining$CellType2)
#==================================================================
PDACSubset1<-subset(PDACSubset1,Condition%in%"Tumor")
table(PDACSubset1$CellType2)
Idents(PDACSubset1)<-"CellType2"
small<-subset(PDACSubset1,downsample=3000)
Idents(small)<-"CellType2"
#================================================================== #Find Markers
DefaultAssay(small)<-"RNA"
pdacfullmarkers <- FindAllMarkers(small,min.pct = 0.2,min.diff.pct = 0.1,test.use = "MAST",only.pos = F)
alltop10 <- pdacfullmarkers %>% group_by(cluster) %>% top_n(n = 100, wt = avg_log2FC)
alltoppval <- pdacfullmarkers %>% group_by(cluster) %>% top_n(n = -100, wt = p_val_adj)
write.csv(pdacfullmarkers , file = "pdacfullmarkers2022.csv", row.names=FALSE)
#=========================================
```

# Global Secretome
```{r}
# Filter out Secretome Hits within Marker Table per Celltype
#===========================================================
set3<-c("FSIP2.TAM","GRN.TAM","Classical.Mono","mDC","LAMP3.DC","SPP1.TAM","Resident.Mac")
geneset1<-subset(alltop10[alltop10$cluster%in%set3,],avg_log2FC>0.8)
#==================================================================
myeloidsec<-intersect(geneset1$gene,c(gene_lists$secretome))
set3<-c("Schwann","iCAF","csCAF","smPSC","qPSC")
geneset1<-subset(alltop10[alltop10$cluster%in%set3,],avg_log2FC>0.8)
#==================================================================
stromasec<-intersect(geneset1$gene,c(gene_lists$secretome))
set3<-c("T.Reg","Plasma","Cytotoxic.CD8.T","Dysfunctional.CD8","Early.CD8","Naive.CD4.T.Cell","Immature.B.Cell","Mem.B.Cell")
geneset1<-subset(alltop10[alltop10$cluster%in%set3,],avg_log2FC>0.8)
lymphosec<-intersect(geneset1$gene,c(gene_lists$secretome))
set3<-c("Tip_EC","MT1X_EC","Venous_EC","Arterial_EC","EHT_EC")
geneset1<-subset(alltop10[alltop10$cluster%in%set3,],avg_log2FC>0.8)
endosec<-intersect(geneset1$gene,c(gene_lists$secretome))
set3<-c("Metaplastic","Acinar","Normal.Duct","Neoplastic")
geneset1<-subset(alltop10[alltop10$cluster%in%set3,],avg_log2FC>0.8)
episec<-intersect(geneset1$gene,c(gene_lists$secretome))
#=========================================================# Set X-axis Cell ordering 
small$CellType3<-small$CellType2
small$CellType3<-droplevels(small$CellType3)
small$CellType3<-factor(small$CellType3,levels=c(
"smPSC","qPSC","csCAF","myCAF","iCAF","Schwann",
"MT1X_EC","Tip_EC","Venous_EC","Arterial_EC","EHT_EC",
"Classical.Mono","SPP1.TAM","GRN.TAM","FSIP2.TAM","Resident.Mac","mDC","LAMP3.DC","Naive.CD4.T.Cell","Early.CD8","Dysfunctional.CD8","Cytotoxic.CD8.T","T.Reg","Immature.B.Cell","Mem.B.Cell","Plasma","Neoplastic","Normal.Duct","Acinar",
"Metaplastic"))
small$CellType3<-factor(small$CellType3,levels=rev(levels(small$CellType3)))
Idents(small)<-"CellType3"
#============================================ # Figure DotPlot
DotPlot(small,features=unique(c(stromasec,endosec,myeloidsec,lymphosec,episec)),cluster.idents=F,col.min=0,col.max=6,dot.min=0.01,scale.by = "size",dot.scale=6,cols=c("ghostwhite","blue"))+theme(axis.text.x = element_text(angle = 90,  hjust = 1))
```

# Global Cell Surface - Contact DotPlot
```{r}
#================================================ Filter out ECM/Contact hits in marker results
set3<-c("FSIP2.TAM","GRN.TAM","Classical.Mono","mDC","LAMP3.DC","SPP1.TAM","Resident.Mac")
geneset1<-subset(alltop10[alltop10$cluster%in%set3,],avg_log2FC>0.8)
myeloidsec<-intersect(geneset1$gene,c(gene_lists$ecm,gene_lists$contact))
set3<-c("Schwann","iCAF","csCAF","smPSC","qPSC")
geneset1<-subset(alltop10[alltop10$cluster%in%set3,],avg_log2FC>0.8)
stromasec<-intersect(geneset1$gene,c(gene_lists$ecm,gene_lists$contact))
set3<-c("T.Reg","Plasma","Cytotoxic.CD8.T","Dysfunctional.CD8","Early.CD8","Naive.CD4.T.Cell","Immature.B.Cell","Mem.B.Cell")
geneset1<-subset(alltop10[alltop10$cluster%in%set3,],avg_log2FC>0.8)
lymphosec<-intersect(geneset1$gene,c(gene_lists$ecm,gene_lists$contact))
set3<-c("Tip_EC","MT1X_EC","Venous_EC","Arterial_EC","EHT_EC")
geneset1<-subset(alltop10[alltop10$cluster%in%set3,],avg_log2FC>0.8)
endosec<-intersect(geneset1$gene,c(gene_lists$ecm,gene_lists$contact))
set3<-c("Metaplastic","Acinar","Normal.Duct","Neoplastic")
geneset1<-subset(alltop10[alltop10$cluster%in%set3,],avg_log2FC>0.8)
episec<-intersect(geneset1$gene,c(gene_lists$ecm,gene_lists$contact))
#========================================== # Figure DotPlot
DotPlot(small,features=unique(c(stromasec,endosec,myeloidsec,lymphosec,episec)),cluster.idents=F,col.min=0,col.max=6,dot.min=0.01,scale.by = "size",dot.scale=6,cols=c("ghostwhite","blue"))+theme(axis.text.x = element_text(angle = 90,  hjust = 1))
```
